version: "3.7"
services:
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/wallabag/web/assets/images
    environment:
      SYMFONY__ENV__DOMAIN_NAME: https://${APP_DOMAIN}
    networks:
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.wallabag-web-redirect.redirectscheme.scheme: https
      traefik.http.services.wallabag.loadbalancer.server.port: 80
      traefik.http.routers.wallabag-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wallabag-insecure.entrypoints: web
      traefik.http.routers.wallabag-insecure.service: wallabag
      traefik.http.routers.wallabag-insecure.middlewares: wallabag-web-redirect
      traefik.http.routers.wallabag.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.wallabag.entrypoints: websecure
      traefik.http.routers.wallabag.service: wallabag
      traefik.http.routers.wallabag.tls.certresolver: myresolver
      traefik.http.routers.wallabag-local-insecure.rule: Host(`wallabag.${LOCAL_DOMAIN}`)
      traefik.http.routers.wallabag-local-insecure.entrypoints: web
      traefik.http.routers.wallabag-local-insecure.service: wallabag
      traefik.http.routers.wallabag-local-insecure.middlewares: wallabag-web-redirect
      traefik.http.routers.wallabag-local.rule: Host(`wallabag.${LOCAL_DOMAIN}`)
      traefik.http.routers.wallabag-local.entrypoints: websecure
      traefik.http.routers.wallabag-local.service: wallabag
      traefik.http.routers.wallabag-local.tls: true
      runtipi.managed: true
